package peterfajdiga.guituner.general;

public class Tone {

    public double frequency;
    public String name;

    // don't allow creation of a new Tone
    private Tone(final double frequency, final String name) {
        this.frequency = frequency;
        this.name = name;
    }

    public static final Tone C0   = new Tone(ToneFrequencies.C0 , "C0");
    public static final Tone C0s  = new Tone(ToneFrequencies.C0s, "C0#");
    public static final Tone D0   = new Tone(ToneFrequencies.D0 , "D0");
    public static final Tone D0s  = new Tone(ToneFrequencies.D0s, "D0#");
    public static final Tone E0   = new Tone(ToneFrequencies.E0 , "E0");
    public static final Tone F0   = new Tone(ToneFrequencies.F0 , "F0");
    public static final Tone F0s  = new Tone(ToneFrequencies.F0s, "F0#");
    public static final Tone G0   = new Tone(ToneFrequencies.G0 , "G0");
    public static final Tone G0s  = new Tone(ToneFrequencies.G0s, "G0#");
    public static final Tone A0   = new Tone(ToneFrequencies.A0 , "A0");
    public static final Tone A0s  = new Tone(ToneFrequencies.A0s, "A0#");
    public static final Tone B0   = new Tone(ToneFrequencies.B0 , "B0");
    public static final Tone C1   = new Tone(ToneFrequencies.C1 , "C1");
    public static final Tone C1s  = new Tone(ToneFrequencies.C1s, "C1#");
    public static final Tone D1   = new Tone(ToneFrequencies.D1 , "D1");
    public static final Tone D1s  = new Tone(ToneFrequencies.D1s, "D1#");
    public static final Tone E1   = new Tone(ToneFrequencies.E1 , "E1");
    public static final Tone F1   = new Tone(ToneFrequencies.F1 , "F1");
    public static final Tone F1s  = new Tone(ToneFrequencies.F1s, "F1#");
    public static final Tone G1   = new Tone(ToneFrequencies.G1 , "G1");
    public static final Tone G1s  = new Tone(ToneFrequencies.G1s, "G1#");
    public static final Tone A1   = new Tone(ToneFrequencies.A1 , "A1");
    public static final Tone A1s  = new Tone(ToneFrequencies.A1s, "A1#");
    public static final Tone B1   = new Tone(ToneFrequencies.B1 , "B1");
    public static final Tone C2   = new Tone(ToneFrequencies.C2 , "C2");
    public static final Tone C2s  = new Tone(ToneFrequencies.C2s, "C2#");
    public static final Tone D2   = new Tone(ToneFrequencies.D2 , "D2");
    public static final Tone D2s  = new Tone(ToneFrequencies.D2s, "D2#");
    public static final Tone E2   = new Tone(ToneFrequencies.E2 , "E2");
    public static final Tone F2   = new Tone(ToneFrequencies.F2 , "F2");
    public static final Tone F2s  = new Tone(ToneFrequencies.F2s, "F2#");
    public static final Tone G2   = new Tone(ToneFrequencies.G2 , "G2");
    public static final Tone G2s  = new Tone(ToneFrequencies.G2s, "G2#");
    public static final Tone A2   = new Tone(ToneFrequencies.A2 , "A2");
    public static final Tone A2s  = new Tone(ToneFrequencies.A2s, "A2#");
    public static final Tone B2   = new Tone(ToneFrequencies.B2 , "B2");
    public static final Tone C3   = new Tone(ToneFrequencies.C3 , "C3");
    public static final Tone C3s  = new Tone(ToneFrequencies.C3s, "C3#");
    public static final Tone D3   = new Tone(ToneFrequencies.D3 , "D3");
    public static final Tone D3s  = new Tone(ToneFrequencies.D3s, "D3#");
    public static final Tone E3   = new Tone(ToneFrequencies.E3 , "E3");
    public static final Tone F3   = new Tone(ToneFrequencies.F3 , "F3");
    public static final Tone F3s  = new Tone(ToneFrequencies.F3s, "F3#");
    public static final Tone G3   = new Tone(ToneFrequencies.G3 , "G3");
    public static final Tone G3s  = new Tone(ToneFrequencies.G3s, "G3#");
    public static final Tone A3   = new Tone(ToneFrequencies.A3 , "A3");
    public static final Tone A3s  = new Tone(ToneFrequencies.A3s, "A3#");
    public static final Tone B3   = new Tone(ToneFrequencies.B3 , "B3");
    public static final Tone C4   = new Tone(ToneFrequencies.C4 , "C4");
    public static final Tone C4s  = new Tone(ToneFrequencies.C4s, "C4#");
    public static final Tone D4   = new Tone(ToneFrequencies.D4 , "D4");
    public static final Tone D4s  = new Tone(ToneFrequencies.D4s, "D4#");
    public static final Tone E4   = new Tone(ToneFrequencies.E4 , "E4");
    public static final Tone F4   = new Tone(ToneFrequencies.F4 , "F4");
    public static final Tone F4s  = new Tone(ToneFrequencies.F4s, "F4#");
    public static final Tone G4   = new Tone(ToneFrequencies.G4 , "G4");
    public static final Tone G4s  = new Tone(ToneFrequencies.G4s, "G4#");
    public static final Tone A4   = new Tone(ToneFrequencies.A4 , "A4");
    public static final Tone A4s  = new Tone(ToneFrequencies.A4s, "A4#");
    public static final Tone B4   = new Tone(ToneFrequencies.B4 , "B4");
    public static final Tone C5   = new Tone(ToneFrequencies.C5 , "C5");
    public static final Tone C5s  = new Tone(ToneFrequencies.C5s, "C5#");
    public static final Tone D5   = new Tone(ToneFrequencies.D5 , "D5");
    public static final Tone D5s  = new Tone(ToneFrequencies.D5s, "D5#");
    public static final Tone E5   = new Tone(ToneFrequencies.E5 , "E5");
    public static final Tone F5   = new Tone(ToneFrequencies.F5 , "F5");
    public static final Tone F5s  = new Tone(ToneFrequencies.F5s, "F5#");
    public static final Tone G5   = new Tone(ToneFrequencies.G5 , "G5");
    public static final Tone G5s  = new Tone(ToneFrequencies.G5s, "G5#");
    public static final Tone A5   = new Tone(ToneFrequencies.A5 , "A5");
    public static final Tone A5s  = new Tone(ToneFrequencies.A5s, "A5#");
    public static final Tone B5   = new Tone(ToneFrequencies.B5 , "B5");
    public static final Tone C6   = new Tone(ToneFrequencies.C6 , "C6");
    public static final Tone C6s  = new Tone(ToneFrequencies.C6s, "C6#");
    public static final Tone D6   = new Tone(ToneFrequencies.D6 , "D6");
    public static final Tone D6s  = new Tone(ToneFrequencies.D6s, "D6#");
    public static final Tone E6   = new Tone(ToneFrequencies.E6 , "E6");
    public static final Tone F6   = new Tone(ToneFrequencies.F6 , "F6");
    public static final Tone F6s  = new Tone(ToneFrequencies.F6s, "F6#");
    public static final Tone G6   = new Tone(ToneFrequencies.G6 , "G6");
    public static final Tone G6s  = new Tone(ToneFrequencies.G6s, "G6#");
    public static final Tone A6   = new Tone(ToneFrequencies.A6 , "A6");
    public static final Tone A6s  = new Tone(ToneFrequencies.A6s, "A6#");
    public static final Tone B6   = new Tone(ToneFrequencies.B6 , "B6");
    public static final Tone C7   = new Tone(ToneFrequencies.C7 , "C7");
    public static final Tone C7s  = new Tone(ToneFrequencies.C7s, "C7#");
    public static final Tone D7   = new Tone(ToneFrequencies.D7 , "D7");
    public static final Tone D7s  = new Tone(ToneFrequencies.D7s, "D7#");
    public static final Tone E7   = new Tone(ToneFrequencies.E7 , "E7");
    public static final Tone F7   = new Tone(ToneFrequencies.F7 , "F7");
    public static final Tone F7s  = new Tone(ToneFrequencies.F7s, "F7#");
    public static final Tone G7   = new Tone(ToneFrequencies.G7 , "G7");
    public static final Tone G7s  = new Tone(ToneFrequencies.G7s, "G7#");
    public static final Tone A7   = new Tone(ToneFrequencies.A7 , "A7");
    public static final Tone A7s  = new Tone(ToneFrequencies.A7s, "A7#");
    public static final Tone B7   = new Tone(ToneFrequencies.B7 , "B7");
    public static final Tone C8   = new Tone(ToneFrequencies.C8 , "C8");
    public static final Tone C8s  = new Tone(ToneFrequencies.C8s, "C8#");
    public static final Tone D8   = new Tone(ToneFrequencies.D8 , "D8");
    public static final Tone D8s  = new Tone(ToneFrequencies.D8s, "D8#");
    public static final Tone E8   = new Tone(ToneFrequencies.E8 , "E8");
    public static final Tone F8   = new Tone(ToneFrequencies.F8 , "F8");
    public static final Tone F8s  = new Tone(ToneFrequencies.F8s, "F8#");
    public static final Tone G8   = new Tone(ToneFrequencies.G8 , "G8");
    public static final Tone G8s  = new Tone(ToneFrequencies.G8s, "G8#");
    public static final Tone A8   = new Tone(ToneFrequencies.A8 , "A8");
    public static final Tone A8s  = new Tone(ToneFrequencies.A8s, "A8#");
    public static final Tone B8   = new Tone(ToneFrequencies.B8 , "B8");
}
